#!/bin/sh
 
cd /System/Library/Audio/UISounds

mv begin_record.caf.bak begin_record.caf

mv end_record.caf.bak end_record.caf

mv photoShutter.caf.bak photoShutter.caf

declare -a cydia
cydia=($CYDIA)
if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' <&${cydia[0]}"
fi